apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-gh-collector.webhookSecretName" . }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "prometheus-gh-collector.webhookSecretName" .)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $whSecret := (get $secretData "webhook-secret") | default (randAlphaNum 32 | b64enc) }}
  webhook-secret: {{ $whSecret | quote }}
