name: publish

on:
  release:
    types: [created]

# on:
#   pull_request:
#     branches: [main]

jobs:
  terraform_test:
    name: Publish Module
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VERSION: ${{ github.ref_name }}
      REGISTRY: ghcr.io
      GIT_SHA: ${{ github.sha }}
      REPO: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build binary
        run: make build
      - name: Log in to the Container registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Publish to Container registry
        run: |
          make docker-push VERSION=${VERSION} REPO=${REPO} IMG_REGISTRY=${REGISTRY}
      - name: Package & pulish helm chart
        run: |
          make helm-push VERSION=${VERSION} REPO=${REPO} IMG_REGISTRY=${REGISTRY}
      - name: Set up Helm
        # if: steps.chart.outputs.version != ''
        uses: azure/setup-helm@v4.3.1
        with:
          version: v3.19.0
      - name: Helm registry login
        # if: steps.chart.outputs.version != ''
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io \
            --username ${{ github.actor }} \
            --password-stdin
      - name: Package & Publish Helm Chart
        # if: steps.chart.outputs.version != ''
        run: |
          make helm-push VERSION=${VERSION} REPO=${REPO} IMG_REGISTRY=${REGISTRY}
